# примеры API-запросов

# получение объявлений
GET http://localhost:8000/api/advertisements/
Content-Type: application/json

###

# создание объявления неаутентифицированного пользователя
POST http://localhost:8000/api/advertisements/
Content-Type: application/json

{
  "title": "Попытка",
  "description": "Я не залоген"
}
###

# создание объявления АДМИН
POST http://localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token f1c493379e1ca244d865a1527e2912d62b7609a3

{
  "title": "Приличный пользователь",
  "description": "Неприличное сообщение вам"
}

###

# создание объявления юзер test
POST http://localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token 9d7dfd8f2ee407299785b65b3a6b224a1d858e12

{
  "title": "test",
  "description": "Прикол"
}

###

# попытка поменять объявление
PATCH http://localhost:8000/api/advertisements/1/
Content-Type: application/json
Authorization: Token f1c493379e1ca244d865a1527e2912d62b7609a3

{
  "status": "CLOSED"
}

###

# попытка поменять объявление 2
PATCH http://localhost:8000/api/advertisements/1/
Content-Type: application/json
Authorization: Token f1c493379e1ca244d865a1527e2912d62b7609a3

{
  "status": "OPEN"
}

###

# удаление объявления (может только владелец)
DELETE http://localhost:8000/api/advertisements/15/
Content-Type: application/json
Authorization: Token 9d7dfd8f2ee407299785b65b3a6b224a1d858e12

###

# фильтрация по создателю
GET http://localhost:8000/api/advertisements/?search=2
Content-Type: application/json

###

# фильтрация по дате - before
GET http://localhost:8000/api/advertisements/?created_at_before=2021-08-01
Content-Type: application/json

###

# фильтрация по дате 2 - after
GET http://localhost:8000/api/advertisements/?created_at_after=2021-08-01
Content-Type: application/json